DROP DATABASE IF EXISTS burger
CREATE DATABASE burger;
USE burger;

CREATE TABLE Burger (
id INT NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(255),
devoured TINYINT,
PRIMARY KEY(id)
)
    
SELECT * FROM Burger;
