DROP DATABASE IF EXISTS burger
CREATE DATABASE burger;
USE burger;

CREATE TABLE burger (
id INT NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(255),
devoured TINYINT NOT NULL DEFAULT 0,
PRIMARY KEY(id)
)
    
SELECT * FROM burger;
